##########################################
#                                        #
#       #   #  #####  #####  #####       #
#       #   #   #     #      #   #       #
#       #   #    #    #####  #####       #
#       #   #     #   #      ###         #
#       #####  #####  #####  #  ##       #
#                                        #
##########################################

###
GET http://localhost:9080/javaee/api/users/
###
GET http://localhost:9080/javaee/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6
###
GET http://localhost:9080/javaee/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/portrait


########## E X E C U T I O N S ###########

###
GET http://localhost:9080/javaee/api/users/ed6cfb2a-cad7-47dd-9b56-9d1e3c7a4197/executions

###
GET http://localhost:9080/javaee/api/executions/

###
GET http://localhost:9080/javaee/api/executions/f8c3de3d-1fea-4d7c-a8b0-29f63c4c3455





# Get all characters.
###
GET http://localhost:9080/javaee/api/characters

###

# Get single character.

GET http://localhost:9080/javaee/api/characters/525d3e7b-bb1f-4c13-bf17-926d1a12e4c0


# Get single character. Not existing, created later.
###
GET http://localhost:9080/javaee/api/characters/3c6f1eb1-8069-44ab-988f-d7fed2b65d87

###

# Get single character portrait.

GET http://localhost:9080/javaee/api/characters/525d3e7b-bb1f-4c13-bf17-926d1a12e4c0/portrait

###

# Get single character portrait. Not existing, created later.

GET http://localhost:9080/javaee/api/characters/3c6f1eb1-8069-44ab-988f-d7fed2b65d87/portrait

###

# Create new character.

PUT http://localhost:9080/javaee/api/characters/3c6f1eb1-8069-44ab-988f-d7fed2b65d87
Content-Type: application/json

{
  "name": "Sigrid",
  "background": "No one special.",
  "age": 18,
  "strength": 12,
  "constitution": 12,
  "charisma": 12,
  "health": 24,
  "profession": "f5875513-bf7b-4ae1-b8a5-5b70a1b90e76"
}
###

###

# Create character portrait.

PUT http://localhost:9080/javaee/api/characters/3c6f1eb1-8069-44ab-988f-d7fed2b65d87/portrait
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="portrait"; filename="sigrid.png'

< javaee/src/main/resources/pl/edu/pg/eti/kask/rpg/configuration/avatar/sigrid.png
--boundary--

###

# Create new character. Not existing profession.

PUT http://localhost:9080/javaee/api/characters/3c6f1eb1-8069-44ab-988f-d7fed2b65d87
Content-Type: application/json

{
  "name": "Sigrid",
  "background": "No one special.",
  "age": 18,
  "strength": 12,
  "constitution": 12,
  "charisma": 12,
  "profession": "f5875513-bf7b-4ae1-b8a5-5b70a1b90e76"
}

###

# Update character.

PATCH http://localhost:9080/javaee/api/characters/3c6f1eb1-8069-44ab-988f-d7fed2b65d87
Content-Type: application/json

{
  "name": "Sir Sigrid",
  "background": "Someone well known.",
  "age": 30
}

###

# Delete character.

DELETE http://localhost:9080/javaee/api/characters/3c6f1eb1-8069-44ab-988f-d7fed2b65d87

###

# Get all professions.

GET http://localhost:9080/javaee/api/professions

###

# Get all profession characters.

GET http://localhost:9080/javaee/api/professions/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76/characters

###

# Get all profession characters. Not existing.

GET http://localhost:9080/javaee/api/professions/d8b50a43-ed45-4441-9bcb-5db7782b47f6/characters

###

# Get all user characters.

GET http://localhost:9080/javaee/api/users/81e1c2a9-7f57-439b-b53d-6db88b071e4e/characters

###

# Get all user characters. Empty.

GET http://localhost:9080/javaee/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/characters

###

# Get all user characters. Not existing.

GET http://localhost:9080/javaee/api/users/c07cab55-a56f-4d67-b351-175bb7a94b7a/characters
